In [8]:
!pip install sqlalchemy
!pip install pymysql

Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: pymysql in /opt/anaconda3/lib/python3.13/site-packages (1.1.3)

In [9]:
from sqlalchemy import create_engine, text
import pandas as pd 
import os

In [10]:
engine1 = create_engine("mysql+pymysql://root:Mysql@123@localhost:3306/piit")
print(engine1)

Engine(mysql+pymysql://root:***@123@localhost:3306/piit)

In [11]:
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

q("SELECT * FROM students")

In [12]:
import pandas as pd
from sqlalchemy import create_engine
import urllib.parse

In [13]:
def q(sql):
    return pd.read_sql(sql, engine1)

In [14]:
q("SELECT * FROM students")

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '123@localhost' ([Errno 8] nodename nor servname provided, or not known)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [2]:
import pandas as pd
from sqlalchemy import create_engine
import urllib.parse

In [3]:
password = urllib.parse.quote_plus("Mysql@123")

In [4]:
engine1 = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/piit")

In [5]:
def q(sql):
    return pd.read_sql(sql, engine1)

In [6]:
q("SELECT * FROM students")

,id,name,branch,score,exam_date,remarks
0,1,Rick Johnson,Mechanical,63.68,2025-03-30,Average
1,2,Shannon Hall,Electrical,74.35,2024-03-28,Outstanding
2,3,Stephanie Flores,Computer Science,88.97,2024-05-17,Average
3,4,Keith Ferrell,Civil,75.00,2025-06-22,Average
4,5,Corey Allen,Computer Science,63.14,2025-05-17,Needs Improvement
5,6,Brittney Galloway,Computer Science,51.85,2025-02-01,Needs Improvement
6,7,Kathryn Gordon,Electrical,70.88,2023-12-10,Outstanding
7,8,Julia Warren,Electrical,63.07,2023-11-21,Needs Improvement
8,9,Carol Cunningham,Computer Science,87.88,2024-07-29,Good
9,10,Cassidy Crawford,Civil,52.46,2025-02-25,Excellent
10,11,William Sanders,Electronics,53.81,2024-01-02,Average
11,12,Amanda Chapman,Mechanical,58.49,2025-03-04,Outstanding
12,13,Amanda Reese,Electronics,54.26,2023-10-15,Average
13,14,Katherine Morrow,Civil,85.95,2023-09-23,Outstanding
14,15,Daniel Graham,Computer Science,65.00,2024-10-27,Needs Improvement
15,16,Alexander Rivers,Electrical,93.69,2024-11-09,Excellent
16,17,Sarah Gordon,Computer Science,86.08,2023-11-24,Excellent
17,18,Lauren Weaver,Electronics,50.65,2025-01-18,Good
18,19,Kim Herrera,Electronics,54.02,2025-01-18,Average
19,20,Rhonda Sullivan,Civil,88.30,2024-02-04,Outstanding
20,21,Sara Gomez,Electronics,64.88,2024-12-01,Needs Improvement
21,22,Emily Moore,Civil,65.21,2024-03-15,Outstanding
22,23,Robert Delacruz,Civil,51.92,2024-02-15,Good
23,24,Shawn Simon,Computer Science,94.68,2023-12-22,Average
24,25,Danielle Le,Mechanical,91.50,2024-02-28,Outstanding
25,26,Alexandra Alexander,Electronics,55.09,2025-04-13,Outstanding
26,27,Anna Zimmerman,Civil,83.72,2024-10-28,Average
27,28,Michael Johnson,Electronics,78.04,2024-07-05,Average
28,29,Michael Higgins DDS,Computer Science,90.45,2025-02-20,Outstanding
29,30,Jodi Chapman,Electronics,54.13,2025-07-04,Needs Improvement

In [7]:
engine1.dispose()

In [8]:
q("SELECT * FROM emp")

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
2    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
3    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
7    7788   SCOTT    ANALYST  7566.0  1982-12-09  3000.0     NaN      20
8    7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
9    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
10   7876   ADAMS      CLERK  7788.0  1983-01-12  1100.0     NaN      20
11   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
12   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
13   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [9]:
q("SELECT * FROM dept")

   deptno       dname       loc
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON
4    10.0  ACCOUNTING  NEW YORK
5    20.0    RESEARCH    DALLAS
6    30.0       SALES   CHICAGO
7    40.0  OPERATIONS    BOSTON

In [10]:
q('show tables')

  Tables_in_piit
0           dept
1            emp
2       students